/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.krud3.mini_proyecto_4.gui;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author JSMC
 */
public class EditarProductosPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditarProductosPanel
     */
    public EditarProductosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel_btn_generar = new javax.swing.JPanel();
        jLabel_btn_generar = new javax.swing.JLabel();
        jComboBox_marcas = new javax.swing.JComboBox<>();
        jPanel_btn_editar_productos = new javax.swing.JPanel();
        jLabel_btn_editar_productos = new javax.swing.JLabel();
        jPanel_btn_editar_nombre = new javax.swing.JPanel();
        jLabel_btn_editar_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_bg.setBackground(new java.awt.Color(16, 36, 61));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel_btn_generar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_generar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_generar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_generar.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_btn_generar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_generar.setText("Generar");
        jLabel_btn_generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_btn_generarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_generarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_generarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_generarLayout = new javax.swing.GroupLayout(jPanel_btn_generar);
        jPanel_btn_generar.setLayout(jPanel_btn_generarLayout);
        jPanel_btn_generarLayout.setHorizontalGroup(
            jPanel_btn_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_generarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_generarLayout.setVerticalGroup(
            jPanel_btn_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_generarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBox_marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel_btn_editar_productos.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_editar_productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_editar_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_editar_productos.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel_btn_editar_productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_editar_productos.setText("Editar productos");
        jLabel_btn_editar_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_editar_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_editar_productosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_editar_productosLayout = new javax.swing.GroupLayout(jPanel_btn_editar_productos);
        jPanel_btn_editar_productos.setLayout(jPanel_btn_editar_productosLayout);
        jPanel_btn_editar_productosLayout.setHorizontalGroup(
            jPanel_btn_editar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_editar_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_editar_productos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_editar_productosLayout.setVerticalGroup(
            jPanel_btn_editar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_btn_editar_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_editar_productos, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_btn_editar_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_editar_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_editar_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_editar_nombre.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel_btn_editar_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_editar_nombre.setText("Editar nombre marca");
        jLabel_btn_editar_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_editar_nombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_editar_nombreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_editar_nombreLayout = new javax.swing.GroupLayout(jPanel_btn_editar_nombre);
        jPanel_btn_editar_nombre.setLayout(jPanel_btn_editar_nombreLayout);
        jPanel_btn_editar_nombreLayout.setHorizontalGroup(
            jPanel_btn_editar_nombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_editar_nombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_editar_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_editar_nombreLayout.setVerticalGroup(
            jPanel_btn_editar_nombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_btn_editar_nombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_editar_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_nombre.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jTextField_nombre.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_nombre.setText("Escriba el nuevo nombre");
        jTextField_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_nombreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_nombreMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(jPanel_btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_btn_editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_btn_editar_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_marcas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_btn_editar_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_btn_editar_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_nombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_bgLayout = new javax.swing.GroupLayout(jPanel_bg);
        jPanel_bg.setLayout(jPanel_bgLayout);
        jPanel_bgLayout.setHorizontalGroup(
            jPanel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bgLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel_bgLayout.setVerticalGroup(
            jPanel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bgLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        add(jPanel_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 920));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_btn_generarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_generarMouseClicked
        JFrame facturin = new FrameEditarFactura();
        facturin.setVisible(true);
    }//GEN-LAST:event_jLabel_btn_generarMouseClicked

    private void jTextField_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nombreMousePressed
        if(jTextField_nombre.getText().equals("Escriba el nuevo nombre")){
            jTextField_nombre.setText("");
        }
    }//GEN-LAST:event_jTextField_nombreMousePressed

    private void jTextField_nombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nombreMouseExited
        if(jTextField_nombre.getText().equals("")){
            jTextField_nombre.setText("Escriba el nuevo nombre");
        }
    }//GEN-LAST:event_jTextField_nombreMouseExited

    private void jLabel_btn_editar_nombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_editar_nombreMouseEntered
        jPanel_btn_editar_nombre.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_editar_nombreMouseEntered

    private void jLabel_btn_editar_nombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_editar_nombreMouseExited
        jPanel_btn_editar_nombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_editar_nombreMouseExited

    private void jLabel_btn_editar_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_editar_productosMouseEntered
        jPanel_btn_editar_productos.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_editar_productosMouseEntered

    private void jLabel_btn_editar_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_editar_productosMouseExited
        jPanel_btn_editar_productos.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_editar_productosMouseExited

    private void jLabel_btn_generarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_generarMouseEntered
        jPanel_btn_generar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_generarMouseEntered

    private void jLabel_btn_generarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_generarMouseExited
        jPanel_btn_generar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_generarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_marcas;
    private javax.swing.JLabel jLabel_btn_editar_nombre;
    private javax.swing.JLabel jLabel_btn_editar_productos;
    private javax.swing.JLabel jLabel_btn_generar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_bg;
    private javax.swing.JPanel jPanel_btn_editar_nombre;
    private javax.swing.JPanel jPanel_btn_editar_productos;
    private javax.swing.JPanel jPanel_btn_generar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables
}
