/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.krud3.mini_proyecto_4.gui;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author JSMC
 */
public class FrameEditarProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrameEditarProducto
     */
    private int xMouse, yMouse;
    public FrameEditarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_header = new javax.swing.JPanel();
        jPanel_btn_salir = new javax.swing.JPanel();
        jLabel_salir = new javax.swing.JLabel();
        jPanel_titulo = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jPanel_derecho = new javax.swing.JPanel();
        jPanel_btn_guardar = new javax.swing.JPanel();
        jLabel_btn_guardar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_btn_cancelar = new javax.swing.JPanel();
        jLabel_btn_cancelar = new javax.swing.JLabel();
        jPanel_izquierdo = new javax.swing.JPanel();
        jPanel_btn_eliminar = new javax.swing.JPanel();
        jLabel_btn_eliminar = new javax.swing.JLabel();
        jPanel_btn_limpiar = new javax.swing.JPanel();
        jLabel_btn_limpiar = new javax.swing.JLabel();
        jPanel_btn_agregar = new javax.swing.JPanel();
        jLabel_btn_agregar = new javax.swing.JLabel();
        jPanel_btn_actualizar = new javax.swing.JPanel();
        jLabel_btn_actualizar = new javax.swing.JLabel();
        jPanel_eliminar_registro18 = new javax.swing.JPanel();
        jLabel_elimar_registro18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_header.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_header.setPreferredSize(new java.awt.Dimension(823, 50));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });

        jPanel_btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_salir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salir.setText("X");
        jLabel_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_salirLayout = new javax.swing.GroupLayout(jPanel_btn_salir);
        jPanel_btn_salir.setLayout(jPanel_btn_salirLayout);
        jPanel_btn_salirLayout.setHorizontalGroup(
            jPanel_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel_btn_salirLayout.setVerticalGroup(
            jPanel_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headerLayout.createSequentialGroup()
                .addGap(0, 920, Short.MAX_VALUE)
                .addComponent(jPanel_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jPanel_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        jPanel_titulo.setBackground(new java.awt.Color(222, 52, 49));
        jPanel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel_titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("EDITAR PRODUCTO");

        javax.swing.GroupLayout jPanel_tituloLayout = new javax.swing.GroupLayout(jPanel_titulo);
        jPanel_titulo.setLayout(jPanel_tituloLayout);
        jPanel_tituloLayout.setHorizontalGroup(
            jPanel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );
        jPanel_tituloLayout.setVerticalGroup(
            jPanel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 950, 50));

        jPanel_derecho.setBackground(new java.awt.Color(16, 36, 61));
        jPanel_derecho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel_btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_btn_guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_btn_guardarMouseExited(evt);
            }
        });

        jLabel_btn_guardar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel_btn_guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_guardar.setText("GUARDAR");
        jLabel_btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_guardarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_guardarLayout = new javax.swing.GroupLayout(jPanel_btn_guardar);
        jPanel_btn_guardar.setLayout(jPanel_btn_guardarLayout);
        jPanel_btn_guardarLayout.setHorizontalGroup(
            jPanel_btn_guardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_btn_guardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_guardarLayout.setVerticalGroup(
            jPanel_btn_guardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_guardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel_btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_btn_cancelarMouseExited(evt);
            }
        });

        jLabel_btn_cancelar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel_btn_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_cancelar.setText("CANCELAR");
        jLabel_btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_cancelarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_cancelarLayout = new javax.swing.GroupLayout(jPanel_btn_cancelar);
        jPanel_btn_cancelar.setLayout(jPanel_btn_cancelarLayout);
        jPanel_btn_cancelarLayout.setHorizontalGroup(
            jPanel_btn_cancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_cancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_cancelarLayout.setVerticalGroup(
            jPanel_btn_cancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_btn_cancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_derechoLayout = new javax.swing.GroupLayout(jPanel_derecho);
        jPanel_derecho.setLayout(jPanel_derechoLayout);
        jPanel_derechoLayout.setHorizontalGroup(
            jPanel_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_derechoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_derechoLayout.createSequentialGroup()
                        .addComponent(jPanel_btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        jPanel_derechoLayout.setVerticalGroup(
            jPanel_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_derechoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel_derecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 80, 560, 520));

        jPanel_izquierdo.setBackground(new java.awt.Color(247, 58, 54));
        jPanel_izquierdo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel_btn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_btn_eliminarMouseExited(evt);
            }
        });

        jLabel_btn_eliminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_eliminar.setText("ELIMINAR");
        jLabel_btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_eliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_eliminarLayout = new javax.swing.GroupLayout(jPanel_btn_eliminar);
        jPanel_btn_eliminar.setLayout(jPanel_btn_eliminarLayout);
        jPanel_btn_eliminarLayout.setHorizontalGroup(
            jPanel_btn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        jPanel_btn_eliminarLayout.setVerticalGroup(
            jPanel_btn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel_btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_btn_limpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_btn_limpiarMouseExited(evt);
            }
        });

        jLabel_btn_limpiar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_limpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_limpiar.setText("LIMPIAR");
        jLabel_btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_limpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_limpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_limpiarLayout = new javax.swing.GroupLayout(jPanel_btn_limpiar);
        jPanel_btn_limpiar.setLayout(jPanel_btn_limpiarLayout);
        jPanel_btn_limpiarLayout.setHorizontalGroup(
            jPanel_btn_limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_btn_limpiarLayout.setVerticalGroup(
            jPanel_btn_limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_btn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_btn_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_btn_agregarMouseExited(evt);
            }
        });

        jLabel_btn_agregar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_agregar.setText("AGREGAR");
        jLabel_btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_agregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_agregarLayout = new javax.swing.GroupLayout(jPanel_btn_agregar);
        jPanel_btn_agregar.setLayout(jPanel_btn_agregarLayout);
        jPanel_btn_agregarLayout.setHorizontalGroup(
            jPanel_btn_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_btn_agregarLayout.setVerticalGroup(
            jPanel_btn_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel_btn_actualizar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_btn_actualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_btn_actualizarMouseExited(evt);
            }
        });

        jLabel_btn_actualizar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_actualizar.setText("ACTUALIZAR");
        jLabel_btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_actualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_actualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_actualizarLayout = new javax.swing.GroupLayout(jPanel_btn_actualizar);
        jPanel_btn_actualizar.setLayout(jPanel_btn_actualizarLayout);
        jPanel_btn_actualizarLayout.setHorizontalGroup(
            jPanel_btn_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        jPanel_btn_actualizarLayout.setVerticalGroup(
            jPanel_btn_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_eliminar_registro18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_eliminar_registro18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_eliminar_registro18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_eliminar_registro18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_eliminar_registro18MouseExited(evt);
            }
        });

        jLabel_elimar_registro18.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_elimar_registro18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_elimar_registro18.setText("ELIMINAR TODO EL REGISTRO");
        jLabel_elimar_registro18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_elimar_registro18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_elimar_registro18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_elimar_registro18MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_eliminar_registro18Layout = new javax.swing.GroupLayout(jPanel_eliminar_registro18);
        jPanel_eliminar_registro18.setLayout(jPanel_eliminar_registro18Layout);
        jPanel_eliminar_registro18Layout.setHorizontalGroup(
            jPanel_eliminar_registro18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_elimar_registro18, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        jPanel_eliminar_registro18Layout.setVerticalGroup(
            jPanel_eliminar_registro18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_elimar_registro18, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_izquierdoLayout = new javax.swing.GroupLayout(jPanel_izquierdo);
        jPanel_izquierdo.setLayout(jPanel_izquierdoLayout);
        jPanel_izquierdoLayout.setHorizontalGroup(
            jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_izquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_eliminar_registro18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_izquierdoLayout.createSequentialGroup()
                        .addGroup(jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel_btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel_izquierdoLayout.setVerticalGroup(
            jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_izquierdoLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(jPanel_eliminar_registro18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel_izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 390, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_salirMouseClicked

    private void jLabel_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseEntered
        jPanel_btn_salir.setBackground(Color.red);
    }//GEN-LAST:event_jLabel_salirMouseEntered

    private void jLabel_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseExited
        jPanel_btn_salir.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_salirMouseExited

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_btn_guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_guardarMouseEntered
        jPanel_btn_guardar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jLabel_btn_guardarMouseEntered

    private void jPanel_btn_guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_guardarMouseEntered
        jPanel_btn_guardar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jPanel_btn_guardarMouseEntered

    private void jPanel_btn_guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_guardarMouseExited
        jPanel_btn_guardar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_btn_guardarMouseExited

    private void jLabel_btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_cancelarMouseEntered
        jPanel_btn_cancelar.setBackground(Color.RED);
    }//GEN-LAST:event_jLabel_btn_cancelarMouseEntered

    private void jPanel_btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_cancelarMouseEntered
        jPanel_btn_cancelar.setBackground(Color.RED);
    }//GEN-LAST:event_jPanel_btn_cancelarMouseEntered

    private void jPanel_btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_cancelarMouseExited
        jPanel_btn_cancelar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_btn_cancelarMouseExited

    private void jLabel_btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_eliminarMouseEntered
        jPanel_btn_eliminar.setBackground(Color.RED);
    }//GEN-LAST:event_jLabel_btn_eliminarMouseEntered

    private void jLabel_btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_eliminarMouseExited
        jPanel_btn_eliminar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_eliminarMouseExited

    private void jPanel_btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_eliminarMouseEntered
        jPanel_btn_eliminar.setBackground(Color.RED);
    }//GEN-LAST:event_jPanel_btn_eliminarMouseEntered

    private void jPanel_btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_eliminarMouseExited
        jPanel_btn_eliminar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_btn_eliminarMouseExited

    private void jLabel_btn_limpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_limpiarMouseEntered
        jPanel_btn_limpiar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_limpiarMouseEntered

    private void jLabel_btn_limpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_limpiarMouseExited
        jPanel_btn_limpiar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_limpiarMouseExited

    private void jPanel_btn_limpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_limpiarMouseEntered
        jPanel_btn_limpiar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jPanel_btn_limpiarMouseEntered

    private void jPanel_btn_limpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_limpiarMouseExited
        jPanel_btn_limpiar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_btn_limpiarMouseExited

    private void jLabel_btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_agregarMouseEntered
        jPanel_btn_agregar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_agregarMouseEntered

    private void jLabel_btn_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_agregarMouseExited
        jPanel_btn_agregar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_agregarMouseExited

    private void jPanel_btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_agregarMouseEntered
        jPanel_btn_agregar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jPanel_btn_agregarMouseEntered

    private void jPanel_btn_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_agregarMouseExited
        jPanel_btn_agregar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_btn_agregarMouseExited

    private void jLabel_btn_actualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_actualizarMouseEntered
        jPanel_btn_actualizar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_actualizarMouseEntered

    private void jLabel_btn_actualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_actualizarMouseExited
        jPanel_btn_actualizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_actualizarMouseExited

    private void jPanel_btn_actualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_actualizarMouseEntered
        jPanel_btn_actualizar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jPanel_btn_actualizarMouseEntered

    private void jPanel_btn_actualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_btn_actualizarMouseExited
        jPanel_btn_actualizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_btn_actualizarMouseExited

    private void jLabel_elimar_registro18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_elimar_registro18MouseClicked
        JFrame dialogo = new FrameConfirmacion("¿Esta seguro de eliminar todo el registro?");
        dialogo.setVisible(true);
    }//GEN-LAST:event_jLabel_elimar_registro18MouseClicked

    private void jLabel_elimar_registro18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_elimar_registro18MouseEntered
        jPanel_eliminar_registro.setBackground(Color.red);
    }//GEN-LAST:event_jLabel_elimar_registro18MouseEntered

    private void jLabel_elimar_registro18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_elimar_registro18MouseExited
        jPanel_eliminar_registro.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_elimar_registro18MouseExited

    private void jPanel_eliminar_registro18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_eliminar_registro18MouseClicked

    }//GEN-LAST:event_jPanel_eliminar_registro18MouseClicked

    private void jPanel_eliminar_registro18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_eliminar_registro18MouseEntered
        jPanel_eliminar_registro.setBackground(Color.red);
    }//GEN-LAST:event_jPanel_eliminar_registro18MouseEntered

    private void jPanel_eliminar_registro18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_eliminar_registro18MouseExited
        jPanel_eliminar_registro.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel_eliminar_registro18MouseExited

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_btn_actualizar;
    private javax.swing.JLabel jLabel_btn_agregar;
    private javax.swing.JLabel jLabel_btn_cancelar;
    private javax.swing.JLabel jLabel_btn_eliminar;
    private javax.swing.JLabel jLabel_btn_guardar;
    private javax.swing.JLabel jLabel_btn_limpiar;
    private javax.swing.JLabel jLabel_elimar_registro;
    private javax.swing.JLabel jLabel_elimar_registro1;
    private javax.swing.JLabel jLabel_elimar_registro10;
    private javax.swing.JLabel jLabel_elimar_registro11;
    private javax.swing.JLabel jLabel_elimar_registro12;
    private javax.swing.JLabel jLabel_elimar_registro13;
    private javax.swing.JLabel jLabel_elimar_registro14;
    private javax.swing.JLabel jLabel_elimar_registro15;
    private javax.swing.JLabel jLabel_elimar_registro16;
    private javax.swing.JLabel jLabel_elimar_registro17;
    private javax.swing.JLabel jLabel_elimar_registro18;
    private javax.swing.JLabel jLabel_elimar_registro2;
    private javax.swing.JLabel jLabel_elimar_registro3;
    private javax.swing.JLabel jLabel_elimar_registro4;
    private javax.swing.JLabel jLabel_elimar_registro5;
    private javax.swing.JLabel jLabel_elimar_registro6;
    private javax.swing.JLabel jLabel_elimar_registro7;
    private javax.swing.JLabel jLabel_elimar_registro8;
    private javax.swing.JLabel jLabel_elimar_registro9;
    private javax.swing.JLabel jLabel_salir;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_btn_actualizar;
    private javax.swing.JPanel jPanel_btn_agregar;
    private javax.swing.JPanel jPanel_btn_cancelar;
    private javax.swing.JPanel jPanel_btn_eliminar;
    private javax.swing.JPanel jPanel_btn_guardar;
    private javax.swing.JPanel jPanel_btn_limpiar;
    private javax.swing.JPanel jPanel_btn_salir;
    private javax.swing.JPanel jPanel_derecho;
    private javax.swing.JPanel jPanel_eliminar_registro;
    private javax.swing.JPanel jPanel_eliminar_registro1;
    private javax.swing.JPanel jPanel_eliminar_registro10;
    private javax.swing.JPanel jPanel_eliminar_registro11;
    private javax.swing.JPanel jPanel_eliminar_registro12;
    private javax.swing.JPanel jPanel_eliminar_registro13;
    private javax.swing.JPanel jPanel_eliminar_registro14;
    private javax.swing.JPanel jPanel_eliminar_registro15;
    private javax.swing.JPanel jPanel_eliminar_registro16;
    private javax.swing.JPanel jPanel_eliminar_registro17;
    private javax.swing.JPanel jPanel_eliminar_registro18;
    private javax.swing.JPanel jPanel_eliminar_registro2;
    private javax.swing.JPanel jPanel_eliminar_registro3;
    private javax.swing.JPanel jPanel_eliminar_registro4;
    private javax.swing.JPanel jPanel_eliminar_registro5;
    private javax.swing.JPanel jPanel_eliminar_registro6;
    private javax.swing.JPanel jPanel_eliminar_registro7;
    private javax.swing.JPanel jPanel_eliminar_registro8;
    private javax.swing.JPanel jPanel_eliminar_registro9;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_izquierdo;
    private javax.swing.JPanel jPanel_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
