/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.krud3.mini_proyecto_4.gui;

import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;


/**
 *
 * @author JSMC
 */
public class Login extends javax.swing.JFrame {
    
    
    private int xMouse,yMouse;
    private JFrame main_frame;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        main_frame = new MainFrame();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bg = new javax.swing.JPanel();
        jPanel_header = new javax.swing.JPanel();
        jPanel_btn_salir = new javax.swing.JPanel();
        jLabel_salir = new javax.swing.JLabel();
        jPanel_left = new javax.swing.JPanel();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_icon = new javax.swing.JLabel();
        jLabel_inicio_sesion = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_clave = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField_clave = new javax.swing.JPasswordField();
        jPanel_btn_entrar = new javax.swing.JPanel();
        jLabel_btn_entrar = new javax.swing.JLabel();
        jPanel_right = new javax.swing.JPanel();
        jLabel_bienvenido = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel_bg.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_header.setPreferredSize(new java.awt.Dimension(823, 50));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });

        jPanel_btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_salir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salir.setText("X");
        jLabel_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_salirLayout = new javax.swing.GroupLayout(jPanel_btn_salir);
        jPanel_btn_salir.setLayout(jPanel_btn_salirLayout);
        jPanel_btn_salirLayout.setHorizontalGroup(
            jPanel_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel_btn_salirLayout.setVerticalGroup(
            jPanel_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headerLayout.createSequentialGroup()
                .addGap(0, 793, Short.MAX_VALUE)
                .addComponent(jPanel_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jPanel_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_bg.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel_left.setBackground(new java.awt.Color(16, 36, 61));

        jLabel_usuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setText("USUARIO");

        jLabel_icon.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel_icon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcon.png"))); // NOI18N
        jLabel_icon.setText("SALES MANAGEMENT");

        jLabel_inicio_sesion.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_inicio_sesion.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_inicio_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_inicio_sesion.setText("INICIO DE SESION:");

        jTextField_usuario.setBackground(new java.awt.Color(16, 36, 61));
        jTextField_usuario.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jTextField_usuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_usuario.setText("Por favor escriba su usuario");
        jTextField_usuario.setBorder(null);
        jTextField_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMousePressed(evt);
            }
        });

        jLabel_clave.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_clave.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_clave.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_clave.setText("CLAVE");

        jPasswordField_clave.setBackground(new java.awt.Color(16, 36, 61));
        jPasswordField_clave.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField_clave.setText("jPasswordField1");
        jPasswordField_clave.setBorder(null);
        jPasswordField_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField_claveMousePressed(evt);
            }
        });

        jLabel_btn_entrar.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_btn_entrar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_entrar.setText("ENTRAR");
        jLabel_btn_entrar.setToolTipText("");
        jLabel_btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_btn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_btn_entrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_entrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_entrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_btn_entrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_entrarLayout = new javax.swing.GroupLayout(jPanel_btn_entrar);
        jPanel_btn_entrar.setLayout(jPanel_btn_entrarLayout);
        jPanel_btn_entrarLayout.setHorizontalGroup(
            jPanel_btn_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        jPanel_btn_entrarLayout.setVerticalGroup(
            jPanel_btn_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_leftLayout = new javax.swing.GroupLayout(jPanel_left);
        jPanel_left.setLayout(jPanel_leftLayout);
        jPanel_leftLayout.setHorizontalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_leftLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon))
                .addGap(60, 60, 60))
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel_clave)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel_inicio_sesion)
                    .addComponent(jLabel_usuario)
                    .addComponent(jTextField_usuario)
                    .addComponent(jPasswordField_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_leftLayout.setVerticalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_inicio_sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel_clave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jPanel_bg.add(jPanel_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 508, 540));

        jPanel_right.setBackground(new java.awt.Color(247, 58, 54));

        jLabel_bienvenido.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel_bienvenido.setForeground(new java.awt.Color(16, 36, 61));
        jLabel_bienvenido.setText("Bienvienido");

        jLabel_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_rightLayout = new javax.swing.GroupLayout(jPanel_right);
        jPanel_right.setLayout(jPanel_rightLayout);
        jPanel_rightLayout.setHorizontalGroup(
            jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_rightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_bienvenido)
                .addGap(29, 29, 29))
            .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_rightLayout.setVerticalGroup(
            jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_rightLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel_bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel_bg.add(jPanel_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 315, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se encarga de inicializar las variables que capturan la posicion del mouse
     * en la barra del header.
     * @param evt evento causado por MouseEvent.
     */
    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    /**
     * Este metodo establece la localizacion de la ventana en el eje seleccionado
     * @param evt evento causado por MouseEvent
     */
    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged
    
    /**
     * Este metodo se encarga de cerrar la ventana cuando se presiona sobre
     * el jLabel transformado en boton
     * @param evt evento causado por MouseEvent
     */
    private void jLabel_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_salirMouseClicked
    /**
     * Este metodo se encarga decambiar el color del boton panel que sirve de
     * "exit" a rojo cuando el mouse pase sobre el 
     * @param evt evento causado por MouseEvent 
     */
    private void jLabel_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseEntered
        jPanel_btn_salir.setBackground(Color.red);
        
        
    }//GEN-LAST:event_jLabel_salirMouseEntered
    /**
     * Este metodo se encarga decambiar el color del boton panel que sirve de
     * "exit" a blanco cuando el mouse deje de estar sobre el 
     * @param evt evento causado por MouseEvent 
     */
    private void jLabel_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseExited
        jPanel_btn_salir.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_salirMouseExited
    /**
     * Este metodo se encarga de cambiar el color del boton cuando el mouse
     * esta sobre el
     * @param evt Evento causado por MouseEvent
     */
    private void jLabel_btn_entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_entrarMouseEntered
        jPanel_btn_entrar.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel_btn_entrarMouseEntered
    /**
     * Este metodo se encarga de cambiar el color del boton cuando el mouse
     * no este sobre el
     * @param evt Evento causado por MouseEvent
     */
    private void jLabel_btn_entrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_entrarMouseExited
        jPanel_btn_entrar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_entrarMouseExited
    
    private void jTextField_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuarioMouseClicked
    
    private void jLabel_btn_entrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_entrarMousePressed
        
    }//GEN-LAST:event_jLabel_btn_entrarMousePressed
    /**
     * Metodo que se encarga de vaciar el campo de la clave
     * cuando se de click en el, tambien tiene en cuenta el campo de 
     * donde se ingresa el usuario y solo remplaza por vacio cuando el texto es igual
     * al original
     * @param evt Evento causado por el MouseEvent
     */
    private void jPasswordField_claveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_claveMousePressed
        if(String.valueOf(jPasswordField_clave.getPassword()).equals("jPasswordField1")){
            jPasswordField_clave.setText("");
            jPasswordField_clave.setForeground(Color.WHITE);
        }
        if(jTextField_usuario.getText().isEmpty()){
            jTextField_usuario.setText("Por favor escriba su usuario");
            jTextField_usuario.setForeground(Color.GRAY);
            
        }
        
    }//GEN-LAST:event_jPasswordField_claveMousePressed
    /**
     * Metodo que se encarga de vaciar el campo de "Ingrese su usuario"
     * cuando se de click en el tambien tiene en cuenta el campo de 
     * password y solo remplaza por vacio cuando el texto es igual
     * al original
     * @param evt Evento causado por el MouseEvent
     */
    private void jTextField_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMousePressed
        if(jTextField_usuario.getText().equals("Por favor escriba su usuario")){
            jTextField_usuario.setText("");
            jTextField_usuario.setForeground(Color.WHITE);
        }
        if(String.valueOf(jPasswordField_clave.getPassword()).isEmpty()){
            jPasswordField_clave.setText("jPasswordField1");
            jPasswordField_clave.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_jTextField_usuarioMousePressed

    /**
     * Metodo que se encargaria de validar los usuarios para posteriormente 
     * al recibir un click abrir el siguiente JFrame y cerrar el JFrame de login
     * @param evt evento causado por MouseEvent
     */
    private void jLabel_btn_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_entrarMouseClicked
        
        this.dispose();
        main_frame.setVisible(true);
    }//GEN-LAST:event_jLabel_btn_entrarMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_bienvenido;
    private javax.swing.JLabel jLabel_btn_entrar;
    private javax.swing.JLabel jLabel_clave;
    private javax.swing.JLabel jLabel_icon;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JLabel jLabel_inicio_sesion;
    private javax.swing.JLabel jLabel_salir;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel_bg;
    private javax.swing.JPanel jPanel_btn_entrar;
    private javax.swing.JPanel jPanel_btn_salir;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_left;
    private javax.swing.JPanel jPanel_right;
    private javax.swing.JPasswordField jPasswordField_clave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
