/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.krud3.mini_proyecto_4.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author JSMC
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int xMouse,yMouse;
    private JPanel panel_ventas,panel_facturas,panel_productos;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        panel_ventas = new TotalVentasPanel();
        panel_facturas = new ReporteFacturasPanel();
        panel_productos = new EditarProductosPanel();
        this.setLocationRelativeTo(null);
    }
    /**
     * Metodo que se encarga de cambiar el panel derecho dependiendo de el boton
     * que presione el usuario
     * @param p El panel que va a remplazar el anterior
     */
    private void ShowPanel(JPanel p){
        p.setSize(1290,920);
        p.setLocation(0, 0);
        
        jPanel_derecho.removeAll();
        jPanel_derecho.add(p, BorderLayout.CENTER);
        jPanel_derecho.revalidate();
        jPanel_derecho.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bg = new javax.swing.JPanel();
        jPanel_izquierdo = new javax.swing.JPanel();
        jPanel_izquierdo_inferior = new javax.swing.JPanel();
        jLabel_img_productIcon = new javax.swing.JLabel();
        jLabel_txt_vereditar = new javax.swing.JLabel();
        jLabel_txt_productos = new javax.swing.JLabel();
        jPanel_izquierdo_superior = new javax.swing.JPanel();
        jLabel_img_ventasIcon = new javax.swing.JLabel();
        jLabel_txt_ventas = new javax.swing.JLabel();
        jPanel_izquierdo_central = new javax.swing.JPanel();
        jLabel_img_facturasIcon = new javax.swing.JLabel();
        jLabel_txt_reportede = new javax.swing.JLabel();
        jLabel_txt_facturas = new javax.swing.JLabel();
        jPanel_derecho = new javax.swing.JPanel();
        jPanel_superior = new javax.swing.JPanel();
        jPanel_salir = new javax.swing.JPanel();
        jLabel_salir = new javax.swing.JLabel();
        jPanel_minimizar = new javax.swing.JPanel();
        jLabel_minimizar = new javax.swing.JLabel();
        jPanel_titulos = new javax.swing.JPanel();
        jLabel_txt_titulos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_izquierdo.setBackground(new java.awt.Color(255, 255, 51));
        jPanel_izquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_izquierdo_inferior.setBackground(new java.awt.Color(247, 58, 54));
        jPanel_izquierdo_inferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_izquierdo_inferior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_izquierdo_inferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_inferiorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_inferiorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_inferiorMouseExited(evt);
            }
        });

        jLabel_img_productIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productosIcon.png"))); // NOI18N
        jLabel_img_productIcon.setToolTipText("");
        jLabel_img_productIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_img_productIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_img_productIconMouseEntered(evt);
            }
        });

        jLabel_txt_vereditar.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_txt_vereditar.setForeground(new java.awt.Color(16, 36, 61));
        jLabel_txt_vereditar.setText("Ver o editar");
        jLabel_txt_vereditar.setToolTipText("");
        jLabel_txt_vereditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_txt_vereditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_txt_vereditarMouseEntered(evt);
            }
        });

        jLabel_txt_productos.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_txt_productos.setForeground(new java.awt.Color(16, 36, 61));
        jLabel_txt_productos.setText("productos");
        jLabel_txt_productos.setToolTipText("");
        jLabel_txt_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_txt_productosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_txt_productosMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel_izquierdo_inferiorLayout = new javax.swing.GroupLayout(jPanel_izquierdo_inferior);
        jPanel_izquierdo_inferior.setLayout(jPanel_izquierdo_inferiorLayout);
        jPanel_izquierdo_inferiorLayout.setHorizontalGroup(
            jPanel_izquierdo_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_izquierdo_inferiorLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel_izquierdo_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_txt_vereditar)
                    .addComponent(jLabel_txt_productos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel_img_productIcon)
                .addGap(30, 30, 30))
        );
        jPanel_izquierdo_inferiorLayout.setVerticalGroup(
            jPanel_izquierdo_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_izquierdo_inferiorLayout.createSequentialGroup()
                .addGroup(jPanel_izquierdo_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_izquierdo_inferiorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel_img_productIcon))
                    .addGroup(jPanel_izquierdo_inferiorLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel_txt_vereditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_txt_productos)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel_izquierdo.add(jPanel_izquierdo_inferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 630, 349));

        jPanel_izquierdo_superior.setBackground(new java.awt.Color(247, 58, 54));
        jPanel_izquierdo_superior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_izquierdo_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_izquierdo_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_superiorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_superiorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_superiorMouseExited(evt);
            }
        });

        jLabel_img_ventasIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventasIcon.png"))); // NOI18N
        jLabel_img_ventasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_img_ventasIconMouseClicked(evt);
            }
        });

        jLabel_txt_ventas.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_txt_ventas.setForeground(new java.awt.Color(16, 36, 61));
        jLabel_txt_ventas.setText("Ventas totales");
        jLabel_txt_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_txt_ventasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_izquierdo_superiorLayout = new javax.swing.GroupLayout(jPanel_izquierdo_superior);
        jPanel_izquierdo_superior.setLayout(jPanel_izquierdo_superiorLayout);
        jPanel_izquierdo_superiorLayout.setHorizontalGroup(
            jPanel_izquierdo_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_izquierdo_superiorLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel_txt_ventas)
                .addGap(33, 33, 33)
                .addComponent(jLabel_img_ventasIcon)
                .addContainerGap())
        );
        jPanel_izquierdo_superiorLayout.setVerticalGroup(
            jPanel_izquierdo_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_izquierdo_superiorLayout.createSequentialGroup()
                .addGroup(jPanel_izquierdo_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img_ventasIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_izquierdo_superiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_txt_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(0, 73, Short.MAX_VALUE))
        );

        jPanel_izquierdo.add(jPanel_izquierdo_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 346));

        jPanel_izquierdo_central.setBackground(new java.awt.Color(247, 58, 54));
        jPanel_izquierdo_central.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_izquierdo_central.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_izquierdo_central.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_centralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_centralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_izquierdo_centralMouseExited(evt);
            }
        });

        jLabel_img_facturasIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facturasIcon2.png"))); // NOI18N
        jLabel_img_facturasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_img_facturasIconMouseClicked(evt);
            }
        });

        jLabel_txt_reportede.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_txt_reportede.setForeground(new java.awt.Color(16, 36, 61));
        jLabel_txt_reportede.setText("Reporte de");
        jLabel_txt_reportede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_txt_reportedeMouseClicked(evt);
            }
        });

        jLabel_txt_facturas.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_txt_facturas.setForeground(new java.awt.Color(16, 36, 61));
        jLabel_txt_facturas.setText("facturas");
        jLabel_txt_facturas.setToolTipText("");
        jLabel_txt_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_txt_facturasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_izquierdo_centralLayout = new javax.swing.GroupLayout(jPanel_izquierdo_central);
        jPanel_izquierdo_central.setLayout(jPanel_izquierdo_centralLayout);
        jPanel_izquierdo_centralLayout.setHorizontalGroup(
            jPanel_izquierdo_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_izquierdo_centralLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel_izquierdo_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_txt_reportede)
                    .addComponent(jLabel_txt_facturas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel_img_facturasIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel_izquierdo_centralLayout.setVerticalGroup(
            jPanel_izquierdo_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_izquierdo_centralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_img_facturasIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_izquierdo_centralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_txt_reportede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_txt_facturas)
                .addGap(106, 106, 106))
        );

        jPanel_izquierdo.add(jPanel_izquierdo_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 346, 630, 346));

        jPanel_bg.add(jPanel_izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 1040));

        jPanel_derecho.setBackground(new java.awt.Color(16, 36, 61));
        jPanel_derecho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel_derechoLayout = new javax.swing.GroupLayout(jPanel_derecho);
        jPanel_derecho.setLayout(jPanel_derechoLayout);
        jPanel_derechoLayout.setHorizontalGroup(
            jPanel_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1288, Short.MAX_VALUE)
        );
        jPanel_derechoLayout.setVerticalGroup(
            jPanel_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );

        jPanel_bg.add(jPanel_derecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 1290, 920));

        jPanel_superior.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_superiorMouseDragged(evt);
            }
        });
        jPanel_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_superiorMousePressed(evt);
            }
        });
        jPanel_superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_salir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_salir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salir.setText("X");
        jLabel_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_salirLayout = new javax.swing.GroupLayout(jPanel_salir);
        jPanel_salir.setLayout(jPanel_salirLayout);
        jPanel_salirLayout.setHorizontalGroup(
            jPanel_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel_salirLayout.setVerticalGroup(
            jPanel_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel_superior.add(jPanel_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 0, -1, -1));

        jPanel_minimizar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_minimizar.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel_minimizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimizar.setText("_");
        jLabel_minimizar.setToolTipText("");
        jLabel_minimizar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_minimizarLayout = new javax.swing.GroupLayout(jPanel_minimizar);
        jPanel_minimizar.setLayout(jPanel_minimizarLayout);
        jPanel_minimizarLayout.setHorizontalGroup(
            jPanel_minimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_minimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel_minimizarLayout.setVerticalGroup(
            jPanel_minimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_minimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel_superior.add(jPanel_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, -1, -1));

        jPanel_bg.add(jPanel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 40));

        jPanel_titulos.setBackground(new java.awt.Color(16, 36, 61));
        jPanel_titulos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel_txt_titulos.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel_txt_titulos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_txt_titulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_txt_titulos.setText("Bienvenido a la aplicacion principal");

        javax.swing.GroupLayout jPanel_titulosLayout = new javax.swing.GroupLayout(jPanel_titulos);
        jPanel_titulos.setLayout(jPanel_titulosLayout);
        jPanel_titulosLayout.setHorizontalGroup(
            jPanel_titulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_txt_titulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)
        );
        jPanel_titulosLayout.setVerticalGroup(
            jPanel_titulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_txt_titulos, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        jPanel_bg.add(jPanel_titulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 1290, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que se encarga de cambiar el color del "boton" cuando el mouse
     * este sobre el
     * @param evt Evento causado por MouseEvent
     */
    
    private void jLabel_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseEntered
        jPanel_minimizar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabel_minimizarMouseEntered

    /**
     * Metodo que se encarga de cambiar el color del "boton" cuando el mouse
     * NO este sobre el
     * @param evt Evento causado por MouseEvent
     */
    
    private void jLabel_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseExited
        jPanel_minimizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_minimizarMouseExited

    /**
     * Metodo que se encarga de cambiar el color del "boton" cuando el mouse
     * este sobre el
     * @param evt Evento causado por MouseEvent
     */
    
    private void jLabel_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseEntered
        jPanel_salir.setBackground(Color.red);
    }//GEN-LAST:event_jLabel_salirMouseEntered

    /**
     * Metodo que se encarga de cambiar el color del "boton" cuando el mouse
     * NO este sobre el
     * @param evt Evento causado por MouseEvent
     */
    private void jLabel_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseExited
        jPanel_salir.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_salirMouseExited
    /**
     * Metodo que se encarga de cerrar la ventana causada por dar click
     * @param evt  Evento causado por MouseEvent
     */
    private void jLabel_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_salirMouseClicked

    /**
     * Metodo que se encarga de minimizar la ventana cuando se da click sobre 
     * el boton
     * @param evt Evento causado por MouseEvent 
     */
    private void jLabel_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizarMouseClicked
    
    /**
     * Metodo que se encarga de capturar los valores x y Y del mouse
     * cuando entra en el panel superior
     * @param evt Evento causado por MouseEvent
     */
    private void jPanel_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_superiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_superiorMousePressed

    /**
     * Metodo que se encarga de ajustar todo el panel dependiendo de como
     * lo acomode el usuario usando MouseDragged capturado por el mouse
     * @param evt Evento causado por MoouseEvent
     */
    private void jPanel_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_superiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel_superiorMouseDragged

    /**
     * Metodo encargado de cambiar el color del panel superior contenido en el
     * panel izquierdo cuando el mouse esta sobre el
     * @param evt Evento capturado por MouseEvent
     */
    private void jPanel_izquierdo_superiorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_superiorMouseEntered
        jPanel_izquierdo_superior.setBackground(new Color(Color.HSBtoRGB(1f,0.78f,87f)));
    }//GEN-LAST:event_jPanel_izquierdo_superiorMouseEntered

    /**
     * Metodo encargado de cambiar el color del panel superior contenido en el
     * panel izquierdo cuando el mouse deja de estar sobre el
     * @param evt Evento capturado por MouseEvent
     */
    private void jPanel_izquierdo_superiorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_superiorMouseExited
        jPanel_izquierdo_superior.setBackground( new Color(Color.HSBtoRGB(1f, 0.78f, 0.97f)));
    }//GEN-LAST:event_jPanel_izquierdo_superiorMouseExited

    /**
     * Metodo encargado de cambiar el color del panel central contenido en el
     * panel izquierddo cuando el mouse esta sobre el
     * @param evt Evento capturado por MouseEvent
     */
    private void jPanel_izquierdo_centralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_centralMouseEntered
        jPanel_izquierdo_central.setBackground(new Color(Color.HSBtoRGB(1f,0.78f,87f)));
    }//GEN-LAST:event_jPanel_izquierdo_centralMouseEntered

    /**
     * Metodo encargado de cambiar el color del panel central contenido en el
     * panel izquierdo cuando el mouse deja de estar sobre el
     * @param evt Evento capturado por MouseEvent
     */
    private void jPanel_izquierdo_centralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_centralMouseExited
        jPanel_izquierdo_central.setBackground( new Color(Color.HSBtoRGB(1f, 0.78f, 0.97f)));
    }//GEN-LAST:event_jPanel_izquierdo_centralMouseExited

    /**
     * Metodo encargado de cambiar el color del panel inferior contenido en el
     * panel izquierdo cuando el mouse esta sobre el
     * @param evt Evento capturado por MouseEvent
     */
    private void jPanel_izquierdo_inferiorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_inferiorMouseEntered
        jPanel_izquierdo_inferior.setBackground(new Color(Color.HSBtoRGB(1f,0.78f,87f)));
    }//GEN-LAST:event_jPanel_izquierdo_inferiorMouseEntered

    /**
     * Metodo encargado de cambiar el color del panel inferior contenido en el
     * panel izquierdo cuando el mouse deja de estar sobre el
     * @param evt Evento capturado por MouseEvent
     */
    private void jPanel_izquierdo_inferiorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_inferiorMouseExited
        jPanel_izquierdo_inferior.setBackground( new Color(Color.HSBtoRGB(1f, 0.78f, 0.97f)));
    }//GEN-LAST:event_jPanel_izquierdo_inferiorMouseExited

    /**
     * Metodo que se encarga de cambiar el color del background del panel
     * que lo contiene cuando el mouse esta sobre el
     * @param evt evento generado por MouseEvent
     */
    private void jLabel_txt_vereditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_vereditarMouseEntered
        jPanel_izquierdo_inferior.setBackground(new Color(Color.HSBtoRGB(1f,0.78f,87f)));
    }//GEN-LAST:event_jLabel_txt_vereditarMouseEntered

    /**
     * Metodo que se encarga de cambiar el color del background del panel
     * que lo contiene cuando el mouse esta sobre el
     * @param evt evento generado por MouseEvent
     */
    private void jLabel_txt_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_productosMouseEntered
        jPanel_izquierdo_inferior.setBackground(new Color(Color.HSBtoRGB(1f,0.78f,87f)));
    }//GEN-LAST:event_jLabel_txt_productosMouseEntered

    /**
     * Metodo que se encarga de cambiar el color del background del panel
     * que lo contiene cuando el mouse esta sobre el
     * @param evt evento generado por MouseEvent
     */
    private void jLabel_img_productIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_img_productIconMouseEntered
        jPanel_izquierdo_inferior.setBackground(new Color(Color.HSBtoRGB(1f,0.78f,87f)));
    }//GEN-LAST:event_jLabel_img_productIconMouseEntered

    private void jPanel_izquierdo_superiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_superiorMouseClicked
        ShowPanel(panel_ventas);
        jLabel_txt_titulos.setText("Total ventas por mes");
    }//GEN-LAST:event_jPanel_izquierdo_superiorMouseClicked

    private void jLabel_img_ventasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_img_ventasIconMouseClicked
        ShowPanel(panel_ventas);
        jLabel_txt_titulos.setText("Total ventas por mes");
    }//GEN-LAST:event_jLabel_img_ventasIconMouseClicked

    private void jLabel_txt_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_ventasMouseClicked
        ShowPanel(panel_ventas);
        jLabel_txt_titulos.setText("Total ventas por mes");
    }//GEN-LAST:event_jLabel_txt_ventasMouseClicked

    private void jPanel_izquierdo_centralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_centralMouseClicked
        ShowPanel(panel_facturas);
        jLabel_txt_titulos.setText("Reporte de facturas");
    }//GEN-LAST:event_jPanel_izquierdo_centralMouseClicked

    private void jLabel_img_facturasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_img_facturasIconMouseClicked
        ShowPanel(panel_facturas);
        jLabel_txt_titulos.setText("Reporte de facturas");
    }//GEN-LAST:event_jLabel_img_facturasIconMouseClicked

    private void jLabel_txt_reportedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_reportedeMouseClicked
        ShowPanel(panel_facturas);
        jLabel_txt_titulos.setText("Reporte de facturas");
    }//GEN-LAST:event_jLabel_txt_reportedeMouseClicked

    private void jLabel_txt_facturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_facturasMouseClicked
        ShowPanel(panel_facturas);
        jLabel_txt_titulos.setText("Reporte de facturas");
    }//GEN-LAST:event_jLabel_txt_facturasMouseClicked

    private void jPanel_izquierdo_inferiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_izquierdo_inferiorMouseClicked
        ShowPanel(panel_productos);
        jLabel_txt_titulos.setText("Ver o editar productos");
    }//GEN-LAST:event_jPanel_izquierdo_inferiorMouseClicked

    private void jLabel_img_productIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_img_productIconMouseClicked
        ShowPanel(panel_productos);
        jLabel_txt_titulos.setText("Ver o editar productos");
    }//GEN-LAST:event_jLabel_img_productIconMouseClicked

    private void jLabel_txt_vereditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_vereditarMouseClicked
        ShowPanel(panel_productos);
        jLabel_txt_titulos.setText("Ver o editar productos");
    }//GEN-LAST:event_jLabel_txt_vereditarMouseClicked

    private void jLabel_txt_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txt_productosMouseClicked
        ShowPanel(panel_productos);
        jLabel_txt_titulos.setText("Ver o editar productos");
    }//GEN-LAST:event_jLabel_txt_productosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_img_facturasIcon;
    private javax.swing.JLabel jLabel_img_productIcon;
    private javax.swing.JLabel jLabel_img_ventasIcon;
    private javax.swing.JLabel jLabel_minimizar;
    private javax.swing.JLabel jLabel_salir;
    private javax.swing.JLabel jLabel_txt_facturas;
    private javax.swing.JLabel jLabel_txt_productos;
    private javax.swing.JLabel jLabel_txt_reportede;
    private javax.swing.JLabel jLabel_txt_titulos;
    private javax.swing.JLabel jLabel_txt_ventas;
    private javax.swing.JLabel jLabel_txt_vereditar;
    private javax.swing.JPanel jPanel_bg;
    private javax.swing.JPanel jPanel_derecho;
    private javax.swing.JPanel jPanel_izquierdo;
    private javax.swing.JPanel jPanel_izquierdo_central;
    private javax.swing.JPanel jPanel_izquierdo_inferior;
    private javax.swing.JPanel jPanel_izquierdo_superior;
    private javax.swing.JPanel jPanel_minimizar;
    private javax.swing.JPanel jPanel_salir;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JPanel jPanel_titulos;
    // End of variables declaration//GEN-END:variables
}
