/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.krud3.mini_proyecto_4.gui;

import java.awt.Color;

/**
 *
 * @author JSMC
 */
public class ReporteFacturasPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReporteFacturasPanel
     */
    public ReporteFacturasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel_btn_generar = new javax.swing.JPanel();
        jLabel_btn_generar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel_btn_editar_factura = new javax.swing.JPanel();
        jLabel_btn_editar_factura = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_dia = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_mes = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_anio = new javax.swing.JLabel();
        jPanel_btn_fecha = new javax.swing.JPanel();
        jLabel_btn_fecha = new javax.swing.JLabel();
        jTextField_dia = new javax.swing.JTextField();
        jTextField_mes = new javax.swing.JTextField();
        jTextField_anio = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel_btn_hora = new javax.swing.JPanel();
        jLabel_btn_hora = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_bg.setBackground(new java.awt.Color(16, 36, 61));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel_btn_generar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_generar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_generar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_generar.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel_btn_generar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_generar.setText("Generar");
        jLabel_btn_generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_generarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_generarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_generarLayout = new javax.swing.GroupLayout(jPanel_btn_generar);
        jPanel_btn_generar.setLayout(jPanel_btn_generarLayout);
        jPanel_btn_generarLayout.setHorizontalGroup(
            jPanel_btn_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_generarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_generarLayout.setVerticalGroup(
            jPanel_btn_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_generarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel_btn_editar_factura.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_editar_factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_editar_factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_editar_factura.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel_btn_editar_factura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_editar_factura.setText("Editar factura");
        jLabel_btn_editar_factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_editar_facturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_editar_facturaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_editar_facturaLayout = new javax.swing.GroupLayout(jPanel_btn_editar_factura);
        jPanel_btn_editar_factura.setLayout(jPanel_btn_editar_facturaLayout);
        jPanel_btn_editar_facturaLayout.setHorizontalGroup(
            jPanel_btn_editar_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btn_editar_facturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_editar_factura, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_btn_editar_facturaLayout.setVerticalGroup(
            jPanel_btn_editar_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_btn_editar_facturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_btn_editar_factura, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_dia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dia.setText("Dia");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_dia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel_mes.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_mes.setText("Mes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel_anio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_anio.setText("Anio");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_anio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_btn_fecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_fecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_fecha.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_fecha.setText("EDITAR FECHA");
        jLabel_btn_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_fechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_fechaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_fechaLayout = new javax.swing.GroupLayout(jPanel_btn_fecha);
        jPanel_btn_fecha.setLayout(jPanel_btn_fechaLayout);
        jPanel_btn_fechaLayout.setHorizontalGroup(
            jPanel_btn_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_btn_fechaLayout.setVerticalGroup(
            jPanel_btn_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField_dia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jTextField_dia.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_dia.setText("DD");

        jTextField_mes.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jTextField_mes.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_mes.setText("MM");

        jTextField_anio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jTextField_anio.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_anio.setText("YYYY");

        jTextField1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("HH:MM");

        jPanel_btn_hora.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_btn_hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btn_hora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_btn_hora.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel_btn_hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_btn_hora.setText("CAMBIAR HORA");
        jLabel_btn_hora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_horaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_horaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btn_horaLayout = new javax.swing.GroupLayout(jPanel_btn_hora);
        jPanel_btn_hora.setLayout(jPanel_btn_horaLayout);
        jPanel_btn_horaLayout.setHorizontalGroup(
            jPanel_btn_horaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_btn_horaLayout.setVerticalGroup(
            jPanel_btn_horaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_btn_hora, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(jPanel_btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_btn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_btn_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_btn_editar_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_btn_hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_btn_editar_factura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_btn_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_dia)
                            .addComponent(jTextField_mes)
                            .addComponent(jTextField_anio)
                            .addComponent(jTextField1)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_bgLayout = new javax.swing.GroupLayout(jPanel_bg);
        jPanel_bg.setLayout(jPanel_bgLayout);
        jPanel_bgLayout.setHorizontalGroup(
            jPanel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bgLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel_bgLayout.setVerticalGroup(
            jPanel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bgLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        add(jPanel_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 920));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_btn_fechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_fechaMouseEntered
        jPanel_btn_fecha.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_fechaMouseEntered

    private void jLabel_btn_fechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_fechaMouseExited
        jPanel_btn_fecha.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_fechaMouseExited

    private void jLabel_btn_horaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_horaMouseEntered
        jPanel_btn_hora.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_horaMouseEntered

    private void jLabel_btn_horaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_horaMouseExited
        jPanel_btn_hora.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_horaMouseExited

    private void jLabel_btn_editar_facturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_editar_facturaMouseEntered
        jPanel_btn_editar_factura.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jLabel_btn_editar_facturaMouseEntered

    private void jLabel_btn_editar_facturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_editar_facturaMouseExited
        jPanel_btn_editar_factura.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_editar_facturaMouseExited

    private void jLabel_btn_generarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_generarMouseEntered
        jPanel_btn_generar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jLabel_btn_generarMouseEntered

    private void jLabel_btn_generarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_generarMouseExited
        jPanel_btn_generar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_btn_generarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel_anio;
    private javax.swing.JLabel jLabel_btn_editar_factura;
    private javax.swing.JLabel jLabel_btn_fecha;
    private javax.swing.JLabel jLabel_btn_generar;
    private javax.swing.JLabel jLabel_btn_hora;
    private javax.swing.JLabel jLabel_dia;
    private javax.swing.JLabel jLabel_mes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_bg;
    private javax.swing.JPanel jPanel_btn_editar_factura;
    private javax.swing.JPanel jPanel_btn_fecha;
    private javax.swing.JPanel jPanel_btn_generar;
    private javax.swing.JPanel jPanel_btn_hora;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_anio;
    private javax.swing.JTextField jTextField_dia;
    private javax.swing.JTextField jTextField_mes;
    // End of variables declaration//GEN-END:variables
}
